sudo: false
language: c++
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
            - deadsnakes
        packages:
            - g++-4.8
            - libboost-test1.55-dev
            - ninja-build
            - python3.5
compiler:
    - gcc
before_install:
    - mkdir -p $HOME/.local/bin
    - ln -s /usr/bin/python3.5 $HOME/.local/bin/python3
    - export PATH="$PATH:$HOME/.local/bin"
    - pip install --user cpp-coveralls
    - git clone https://github.com/mesonbuild/meson.git /tmp/meson
    - cd /tmp/meson
    - ./install_meson.py --prefix $HOME/.local/
script:
    - mkdir build
    - cd build && meson --enable-gcov ..
    - cd build && ninja test
after_success:
    - cd build && coveralls --gcov /usr/bin/gcov-4.8 --gcov-options '\-lp'
