sudo: false
language: c++
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
compiler:
    - gcc
before_install:
    - pip install --user cpp-coveralls
script:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - scons libmode=coverall testmode=coverall
    - ./tests/error_testing
    - ./tests/iterator_testing
    - ./tests/utils_testing
after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
