sudo: false
language: c++
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
        packages:
            - g++-4.8
            - libboost-test1.55-dev
compiler:
    - gcc
before_install:
    - pip install --user cpp-coveralls
script:
    - scons libmode=coverall testmode=coverall CXX="g++-4.8"
    - ./tests/error_testing
    - ./tests/iterator_testing
    - ./tests/utils_testing
after_success:
    - coveralls --gcov /usr/bin/gcov-4.8 --gcov-options '\-lp'
