sudo: false
language: c++
python:
  - "2.7"
  - "3.4"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
        packages:
            - g++-4.8
            - libboost-test1.55-dev
            - ninja-build
compiler:
    - gcc
before_install:
    - mkdir -p $HOME/.local/bin
    - pip install --user cpp-coveralls
    - git clone https://github.com/mesonbuild/meson.git /tmp/meson
    - cd /tmp/meson
    - ./install_meson.py --prefix $HOME/.local/
    - export PATH="$PATH:$HOME/.local/bin"
script:
    - mkdir build && cd build
    - meson --enable-gcov ..
    - ninja test
after_success:
    - coveralls --gcov /usr/bin/gcov-4.8 --gcov-options '\-lp'
