sudo: false
language: c++
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
            - deadsnakes
        packages:
            - g++-4.8
            - libboost-test1.55-dev
            - ninja-build
            - python3.5
            - moreutils
compiler:
    - gcc
before_install:
    - mkdir -p $HOME/.local/bin
    - ln -s /usr/bin/python3.5 $HOME/.local/bin/python3
    - export PATH="$PATH:$HOME/.local/bin"
    - pip install --user cpp-coveralls
    - git clone https://github.com/mesonbuild/meson.git /tmp/meson
    - (cd /tmp/meson && ./install_meson.py --prefix $HOME/.local/)
    - sed 's/self\.check_outputs(gcno_elem, gcno_elem)/self.check_outputs(gcno_elem)/' $HOME/.local/share/meson/ninjabackend.py | sponge $HOME/.local/share/meson/ninjabackend.py
script:
    - mkdir build
    - cd build
    - meson --enable-gcov ..
    - sed 's/ninja_required_version = 1.5.1//' build.ninja | sponge build.ninja
    - ninja test
after_success:
    - coveralls --gcov /usr/bin/gcov-4.8 --gcov-options '\-lp'
