sudo: false
language: c++
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
        packages:
            - g++-4.8
            - libboost-test1.55-dev
            - python3.4
            - ninja-build
compiler:
    - gcc
before_install:
    - pip install --user cpp-coveralls
    - git clone https://github.com/mesonbuild/meson.git /tmp/meson
    - cd /tmp/meson
    - ./install_meson.py --prefix $HOME/.local/
    - export PATH="$PATH:$HOME/.local/bin"
script:
    - mkdir build && cd build
    - meson --enable-gcov ..
    - ninja test
after_success:
    - coveralls --gcov /usr/bin/gcov-4.8 --gcov-options '\-lp'
